### ISSUE TITLE
Nicknames

### ISSUE THREAD

**Issue by PolishDywan** [GuilhermeTrevizani/trevizani-roleplay-server#6]
Nicknames do not work in the latest version of ALT:V

**Comment by GuilhermeTrevizani** [comment]
I think the problem is related with alt.Player.streamedIn when you reconnect.

When you use debug = false, is the problem still happening?

**Comment by PolishDywan** [comment]
> When you use debug = false, is the problem still happening?

Yes

**Comment by GuilhermeTrevizani** [comment]
Fixed. Use new client-side.
