### ISSUE TITLE
Login problem how repair

### ISSUE THREAD

**Issue by nerdzik** [GuilhermeTrevizani/trevizani-roleplay-server#9]
Hi, i use your script for tests and hobby.
I need your help with your login system discord i have problem by:
![image](https://github.com/GuilhermeTrevizani/trevizani-roleplay-server/assets/66621810/3a3a4adf-99cc-4340-a611-b9eeeac1082c)

How repair this problem?

**Comment by nerdzik** [comment]
I have auth with Treviziani App
![image](https://github.com/GuilhermeTrevizani/trevizani-roleplay-server/assets/66621810/6921cb7c-a78f-409a-a98e-696fa72bf503)

**Comment by Galatimus** [comment]
sorry...

**Comment by nerdzik** [comment]
> sorry...

?

**Comment by GuilhermeTrevizani** [comment]
Please try deauthorize and authorize again. You can try create your own Discord application and configure in https://github.com/GuilhermeTrevizani/trevizani-roleplay/blob/71a1b59506441f8b91efbe3addfc213c0f9aeba8/ALTVSERVER/resources/client/helpers/constants.js#L13
